### ISSUE TITLE
RFE: Suppot Docker v2 Plugins

### ISSUE THREAD

**Issue by e4jet** [hpe-storage/dory#17]
dory should support gathering plugin information from docker to detect the path to the socket file.

**Comment by drajen** [comment]
Could this somehow be done dynamically?
Example:
```
{
    "dockerVolumePluginSocketPath": "nimble:latest"
}
```
If `dockerVolumePluginSocketPath` isn't a an absolute path, query the Docker API for plugin ID and get the socket?

**Comment by e4jet** [comment]
Yes, that's is the idea.

**Comment by e4jet** [comment]
created pr  #18 to address this.

**Comment by e4jet** [comment]
added pr #19 to document new capability.
