### ISSUE TITLE
docker volume/system prune can cause persistent volumes to be unintentionally deleted

### ISSUE THREAD

**Issue by e4jet** [hpe-storage/dory#30]
After playing with the beta of [Docker's Kubernetes](https://www.docker.com/kubernetes) and speaking with @cpuguy83 it has become apparent that users of the Docker distro of Kubernetes could potentially shoot themselves in the foot with ```docker volume prune```. Similarly, ```docker system prune --volumes``` could cause problems. The issue here is the classic 'multi-master problem'. The docker engine doesn't know anything about the volumes doryd has created to back Persistent Volumes.  Because these volumes aren't referenced by any docker container, the docker engine sees them as unused and candidates for reclamation.

This hasn't been an issue to date because most k8s users don't interact with the docker command, they use kubectl or equivalent. In the case of the Docker distro though, the user is likely to be interacting with both. This creates a situation where a user of the docker command could disrupt consumers (Deployments or Pods) of Persistent Volumes.

* [docker volume prune](https://docs.docker.com/engine/reference/commandline/volume_prune/)
* [docker system prune --volumes](https://docs.docker.com/engine/reference/commandline/system_prune/)

**Comment by e4jet** [comment]
## Design

The fix for this issue is to annotate the docker volume using a Docker Volume Option at creation that instructs the Docker Volume Driver not to delete this particular volume when ```/VolumeDriver.Remove``` is called.  This new option will be called ```manager``` and will contain the name of the 3rd party manager which created this volume.  When ```/VolumeDriver.Remove``` is called with input that contains the new attribute ```manager``` and the value matches that which was specified in the creation option, only then will the remove actually be triggered.

This allows the docker engine to continue to leverage the ```/VolumeDriver.Remove``` endpoint unchanged, while other managers can retain control over the life cycle of volumes safely.

## Example

1. User creates a persistent volume claim, which is then satisfied by Doryd.
   * The Docker Volume Driver receives the following:
     * ``` /VolumeDriver.Create { "Name": "vol1", "Opts": {"manager":"dory"}}```
1. A user runs ```docker volume prune```.
   * The Docker Volume Driver receives the following:
     * ``` /VolumeDriver.Remove { "Name": "vol1" } ```
   * The Docker Volume Driver **must not** remove this volume.
1. A user runs ```kubectl delete pvc vol1```
   * The Docker Volume Driver receives the following:
     * ``` /VolumeDriver.Remove { "Name": "vol1", "manager":"dory"}```
   * The Docker Volume Driver **must** remove this volume.

**Comment by cpuguy83** [comment]
@e4jet Wondering if it would be easier to create the volume via the docker API instead?

```json
{
  "Image": "<some pause image>",
  "HostConfig":
    { "Mounts": [
      {
        "Type": "volume",
        "Source": "vol_name",
        "Target": "/whatever",
        "VolumeOptions":{ 
          "Driver": {
            "Name": "<driver name>",
            "Options": {}
          }
        }
      }
    ]
  }
}
```

This can also be annotated with kube annotations/labels as well.

**Comment by e4jet** [comment]
Good question @cpuguy83 .  I started there, but ran into two issues:

1. Project Dory was design to be Container Engine agnostic (which is why it talks to the driver directly).
1. My understanding is that any Docker Volume will be subject to deletion via 'prune' regardless of how it was created.  Specifically, any volume not associated with a container will be deleted.

**Comment by cpuguy83** [comment]
@e4jet 

> Project Dory was design to be Container Engine agnostic (which is why it talks to the driver directly).

That's understandable, but this is also the docker volume plugin API. Is this going to be used outside of the docker context?

> My understanding is that any Docker Volume will be subject to deletion via 'prune' regardless of how it was created. Specifically, any volume not associated with a container will be deleted.

That is correct, however creating the volume as specified above there will be a container holding the reference. It also handles the mount.
So essentially mounting the volume means running the container, unmounting is stopping the container.

**Comment by e4jet** [comment]
> That's understandable, but this is also the docker volume plugin API. 

True, but this proposal doesn't change the "real" docker volume api.  It simply extends it for plugins that want to support Dory.

> Is this going to be used outside of the docker context?

Yes, Dory is a core component of HPE's currently a shipping storage integration product for k8s.  Given all the work around the k8s container runtime interface (cri-containerd, cri-o,etc) we want make sure Dory is supported.

> So essentially mounting the volume means running the container, unmounting is stopping the container.
 
Ah, got it.  This is interesting, but would require some re-architecting.  This proposed design doesn't preclude us from moving to this in a later release.
